name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pandas
    - name: Execute python file and compare it output with res_file
      run: |
        python release.py --f ${GITHUB_WORKSPACE}/old_file.txt 
          envA=$(cat ${GITHUB_WORKSPACE}/res_file)
          envB=$(cat ${GITHUB_WORKSPACE}/final)
          if [[ "$envA" == "$envB" ]]
          then
           echo "All is good, file is the same!"
          else
           echo "file isn't same"
           exit 1
          fi
